# Generated by Django 4.2.3 on 2023-07-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to='images/'),
        ),
    ]
