# Generated by Django 4.2.3 on 2023-08-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_github_user_linkedin_user_twitter_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('seminar', 'Seminar')], default='hackathon', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='demo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
