# Generated by Django 4.2.3 on 2023-08-04 01:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_event_cover_photo_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default-hackathon.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[2400, 1600], upload_to='images/'),
        ),
    ]
