# Generated by Django 4.2.3 on 2023-08-04 01:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_event_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/default-hackathon.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[2400, 1600], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/default-avatar.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to='images/'),
        ),
    ]
